// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/role"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/rolepermission"
)

// RolePermissionCreate is the builder for creating a RolePermission entity.
type RolePermissionCreate struct {
	config
	mutation *RolePermissionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *RolePermissionCreate) SetCreatedAt(v time.Time) *RolePermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCreatedAt(v *time.Time) *RolePermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RolePermissionCreate) SetUpdatedAt(v time.Time) *RolePermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableUpdatedAt(v *time.Time) *RolePermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *RolePermissionCreate) SetRoleID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetSection sets the "section" field.
func (_c *RolePermissionCreate) SetSection(v string) *RolePermissionCreate {
	_c.mutation.SetSection(v)
	return _c
}

// SetCollectionID sets the "collection_id" field.
func (_c *RolePermissionCreate) SetCollectionID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetCollectionID(v)
	return _c
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCollectionID(v *uuid.UUID) *RolePermissionCreate {
	if v != nil {
		_c.SetCollectionID(*v)
	}
	return _c
}

// SetCanView sets the "can_view" field.
func (_c *RolePermissionCreate) SetCanView(v bool) *RolePermissionCreate {
	_c.mutation.SetCanView(v)
	return _c
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCanView(v *bool) *RolePermissionCreate {
	if v != nil {
		_c.SetCanView(*v)
	}
	return _c
}

// SetCanCreate sets the "can_create" field.
func (_c *RolePermissionCreate) SetCanCreate(v bool) *RolePermissionCreate {
	_c.mutation.SetCanCreate(v)
	return _c
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCanCreate(v *bool) *RolePermissionCreate {
	if v != nil {
		_c.SetCanCreate(*v)
	}
	return _c
}

// SetCanEdit sets the "can_edit" field.
func (_c *RolePermissionCreate) SetCanEdit(v bool) *RolePermissionCreate {
	_c.mutation.SetCanEdit(v)
	return _c
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCanEdit(v *bool) *RolePermissionCreate {
	if v != nil {
		_c.SetCanEdit(*v)
	}
	return _c
}

// SetCanDelete sets the "can_delete" field.
func (_c *RolePermissionCreate) SetCanDelete(v bool) *RolePermissionCreate {
	_c.mutation.SetCanDelete(v)
	return _c
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableCanDelete(v *bool) *RolePermissionCreate {
	if v != nil {
		_c.SetCanDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RolePermissionCreate) SetID(v uuid.UUID) *RolePermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RolePermissionCreate) SetNillableID(v *uuid.UUID) *RolePermissionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRole sets the "role" edge to the Role entity.
func (_c *RolePermissionCreate) SetRole(v *Role) *RolePermissionCreate {
	return _c.SetRoleID(v.ID)
}

// SetCollection sets the "collection" edge to the Group entity.
func (_c *RolePermissionCreate) SetCollection(v *Group) *RolePermissionCreate {
	return _c.SetCollectionID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_c *RolePermissionCreate) Mutation() *RolePermissionMutation {
	return _c.mutation
}

// Save creates the RolePermission in the database.
func (_c *RolePermissionCreate) Save(ctx context.Context) (*RolePermission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RolePermissionCreate) SaveX(ctx context.Context) *RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RolePermissionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rolepermission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rolepermission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CanView(); !ok {
		v := rolepermission.DefaultCanView
		_c.mutation.SetCanView(v)
	}
	if _, ok := _c.mutation.CanCreate(); !ok {
		v := rolepermission.DefaultCanCreate
		_c.mutation.SetCanCreate(v)
	}
	if _, ok := _c.mutation.CanEdit(); !ok {
		v := rolepermission.DefaultCanEdit
		_c.mutation.SetCanEdit(v)
	}
	if _, ok := _c.mutation.CanDelete(); !ok {
		v := rolepermission.DefaultCanDelete
		_c.mutation.SetCanDelete(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := rolepermission.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RolePermissionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RolePermission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RolePermission.updated_at"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "RolePermission.role_id"`)}
	}
	if _, ok := _c.mutation.Section(); !ok {
		return &ValidationError{Name: "section", err: errors.New(`ent: missing required field "RolePermission.section"`)}
	}
	if v, ok := _c.mutation.Section(); ok {
		if err := rolepermission.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "RolePermission.section": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CanView(); !ok {
		return &ValidationError{Name: "can_view", err: errors.New(`ent: missing required field "RolePermission.can_view"`)}
	}
	if _, ok := _c.mutation.CanCreate(); !ok {
		return &ValidationError{Name: "can_create", err: errors.New(`ent: missing required field "RolePermission.can_create"`)}
	}
	if _, ok := _c.mutation.CanEdit(); !ok {
		return &ValidationError{Name: "can_edit", err: errors.New(`ent: missing required field "RolePermission.can_edit"`)}
	}
	if _, ok := _c.mutation.CanDelete(); !ok {
		return &ValidationError{Name: "can_delete", err: errors.New(`ent: missing required field "RolePermission.can_delete"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "RolePermission.role"`)}
	}
	return nil
}

func (_c *RolePermissionCreate) sqlSave(ctx context.Context) (*RolePermission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RolePermissionCreate) createSpec() (*RolePermission, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePermission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolepermission.Table, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rolepermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Section(); ok {
		_spec.SetField(rolepermission.FieldSection, field.TypeString, value)
		_node.Section = value
	}
	if value, ok := _c.mutation.CanView(); ok {
		_spec.SetField(rolepermission.FieldCanView, field.TypeBool, value)
		_node.CanView = value
	}
	if value, ok := _c.mutation.CanCreate(); ok {
		_spec.SetField(rolepermission.FieldCanCreate, field.TypeBool, value)
		_node.CanCreate = value
	}
	if value, ok := _c.mutation.CanEdit(); ok {
		_spec.SetField(rolepermission.FieldCanEdit, field.TypeBool, value)
		_node.CanEdit = value
	}
	if value, ok := _c.mutation.CanDelete(); ok {
		_spec.SetField(rolepermission.FieldCanDelete, field.TypeBool, value)
		_node.CanDelete = value
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.CollectionTable,
			Columns: []string{rolepermission.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CollectionID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RolePermissionCreateBulk is the builder for creating many RolePermission entities in bulk.
type RolePermissionCreateBulk struct {
	config
	err      error
	builders []*RolePermissionCreate
}

// Save creates the RolePermission entities in the database.
func (_c *RolePermissionCreateBulk) Save(ctx context.Context) ([]*RolePermission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RolePermission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) SaveX(ctx context.Context) []*RolePermission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
