// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/role"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/rolepermission"
)

// RolePermission is the model entity for the RolePermission schema.
type RolePermission struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID uuid.UUID `json:"role_id,omitempty"`
	// Section holds the value of the "section" field.
	Section string `json:"section,omitempty"`
	// CollectionID holds the value of the "collection_id" field.
	CollectionID *uuid.UUID `json:"collection_id,omitempty"`
	// CanView holds the value of the "can_view" field.
	CanView bool `json:"can_view,omitempty"`
	// CanCreate holds the value of the "can_create" field.
	CanCreate bool `json:"can_create,omitempty"`
	// CanEdit holds the value of the "can_edit" field.
	CanEdit bool `json:"can_edit,omitempty"`
	// CanDelete holds the value of the "can_delete" field.
	CanDelete bool `json:"can_delete,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RolePermissionQuery when eager-loading is set.
	Edges        RolePermissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RolePermissionEdges holds the relations/edges for other nodes in the graph.
type RolePermissionEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// Collection holds the value of the collection edge.
	Collection *Group `json:"collection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RolePermissionEdges) RoleOrErr() (*Role, error) {
	if e.Role != nil {
		return e.Role, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: role.Label}
	}
	return nil, &NotLoadedError{edge: "role"}
}

// CollectionOrErr returns the Collection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RolePermissionEdges) CollectionOrErr() (*Group, error) {
	if e.Collection != nil {
		return e.Collection, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "collection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RolePermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolepermission.FieldCollectionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rolepermission.FieldCanView, rolepermission.FieldCanCreate, rolepermission.FieldCanEdit, rolepermission.FieldCanDelete:
			values[i] = new(sql.NullBool)
		case rolepermission.FieldSection:
			values[i] = new(sql.NullString)
		case rolepermission.FieldCreatedAt, rolepermission.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case rolepermission.FieldID, rolepermission.FieldRoleID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RolePermission fields.
func (_m *RolePermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolepermission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case rolepermission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rolepermission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case rolepermission.FieldRoleID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value != nil {
				_m.RoleID = *value
			}
		case rolepermission.FieldSection:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field section", values[i])
			} else if value.Valid {
				_m.Section = value.String
			}
		case rolepermission.FieldCollectionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field collection_id", values[i])
			} else if value.Valid {
				_m.CollectionID = new(uuid.UUID)
				*_m.CollectionID = *value.S.(*uuid.UUID)
			}
		case rolepermission.FieldCanView:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_view", values[i])
			} else if value.Valid {
				_m.CanView = value.Bool
			}
		case rolepermission.FieldCanCreate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_create", values[i])
			} else if value.Valid {
				_m.CanCreate = value.Bool
			}
		case rolepermission.FieldCanEdit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_edit", values[i])
			} else if value.Valid {
				_m.CanEdit = value.Bool
			}
		case rolepermission.FieldCanDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field can_delete", values[i])
			} else if value.Valid {
				_m.CanDelete = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RolePermission.
// This includes values selected through modifiers, order, etc.
func (_m *RolePermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the RolePermission entity.
func (_m *RolePermission) QueryRole() *RoleQuery {
	return NewRolePermissionClient(_m.config).QueryRole(_m)
}

// QueryCollection queries the "collection" edge of the RolePermission entity.
func (_m *RolePermission) QueryCollection() *GroupQuery {
	return NewRolePermissionClient(_m.config).QueryCollection(_m)
}

// Update returns a builder for updating this RolePermission.
// Note that you need to call RolePermission.Unwrap() before calling this method if this RolePermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RolePermission) Update() *RolePermissionUpdateOne {
	return NewRolePermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RolePermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RolePermission) Unwrap() *RolePermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RolePermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RolePermission) String() string {
	var builder strings.Builder
	builder.WriteString("RolePermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoleID))
	builder.WriteString(", ")
	builder.WriteString("section=")
	builder.WriteString(_m.Section)
	builder.WriteString(", ")
	if v := _m.CollectionID; v != nil {
		builder.WriteString("collection_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("can_view=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanView))
	builder.WriteString(", ")
	builder.WriteString("can_create=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanCreate))
	builder.WriteString(", ")
	builder.WriteString("can_edit=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanEdit))
	builder.WriteString(", ")
	builder.WriteString("can_delete=")
	builder.WriteString(fmt.Sprintf("%v", _m.CanDelete))
	builder.WriteByte(')')
	return builder.String()
}

// RolePermissions is a parsable slice of RolePermission.
type RolePermissions []*RolePermission
