// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/group"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/role"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/rolepermission"
)

// RolePermissionUpdate is the builder for updating RolePermission entities.
type RolePermissionUpdate struct {
	config
	hooks    []Hook
	mutation *RolePermissionMutation
}

// Where appends a list predicates to the RolePermissionUpdate builder.
func (_u *RolePermissionUpdate) Where(ps ...predicate.RolePermission) *RolePermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePermissionUpdate) SetUpdatedAt(v time.Time) *RolePermissionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RolePermissionUpdate) SetRoleID(v uuid.UUID) *RolePermissionUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableRoleID(v *uuid.UUID) *RolePermissionUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetSection sets the "section" field.
func (_u *RolePermissionUpdate) SetSection(v string) *RolePermissionUpdate {
	_u.mutation.SetSection(v)
	return _u
}

// SetNillableSection sets the "section" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableSection(v *string) *RolePermissionUpdate {
	if v != nil {
		_u.SetSection(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *RolePermissionUpdate) SetCollectionID(v uuid.UUID) *RolePermissionUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableCollectionID(v *uuid.UUID) *RolePermissionUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *RolePermissionUpdate) ClearCollectionID() *RolePermissionUpdate {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetCanView sets the "can_view" field.
func (_u *RolePermissionUpdate) SetCanView(v bool) *RolePermissionUpdate {
	_u.mutation.SetCanView(v)
	return _u
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableCanView(v *bool) *RolePermissionUpdate {
	if v != nil {
		_u.SetCanView(*v)
	}
	return _u
}

// SetCanCreate sets the "can_create" field.
func (_u *RolePermissionUpdate) SetCanCreate(v bool) *RolePermissionUpdate {
	_u.mutation.SetCanCreate(v)
	return _u
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableCanCreate(v *bool) *RolePermissionUpdate {
	if v != nil {
		_u.SetCanCreate(*v)
	}
	return _u
}

// SetCanEdit sets the "can_edit" field.
func (_u *RolePermissionUpdate) SetCanEdit(v bool) *RolePermissionUpdate {
	_u.mutation.SetCanEdit(v)
	return _u
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableCanEdit(v *bool) *RolePermissionUpdate {
	if v != nil {
		_u.SetCanEdit(*v)
	}
	return _u
}

// SetCanDelete sets the "can_delete" field.
func (_u *RolePermissionUpdate) SetCanDelete(v bool) *RolePermissionUpdate {
	_u.mutation.SetCanDelete(v)
	return _u
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (_u *RolePermissionUpdate) SetNillableCanDelete(v *bool) *RolePermissionUpdate {
	if v != nil {
		_u.SetCanDelete(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RolePermissionUpdate) SetRole(v *Role) *RolePermissionUpdate {
	return _u.SetRoleID(v.ID)
}

// SetCollection sets the "collection" edge to the Group entity.
func (_u *RolePermissionUpdate) SetCollection(v *Group) *RolePermissionUpdate {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_u *RolePermissionUpdate) Mutation() *RolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RolePermissionUpdate) ClearRole() *RolePermissionUpdate {
	_u.mutation.ClearRole()
	return _u
}

// ClearCollection clears the "collection" edge to the Group entity.
func (_u *RolePermissionUpdate) ClearCollection() *RolePermissionUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RolePermissionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RolePermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePermissionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePermissionUpdate) check() error {
	if v, ok := _u.mutation.Section(); ok {
		if err := rolepermission.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "RolePermission.section": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePermission.role"`)
	}
	return nil
}

func (_u *RolePermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermission.Table, rolepermission.Columns, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Section(); ok {
		_spec.SetField(rolepermission.FieldSection, field.TypeString, value)
	}
	if value, ok := _u.mutation.CanView(); ok {
		_spec.SetField(rolepermission.FieldCanView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanCreate(); ok {
		_spec.SetField(rolepermission.FieldCanCreate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanEdit(); ok {
		_spec.SetField(rolepermission.FieldCanEdit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanDelete(); ok {
		_spec.SetField(rolepermission.FieldCanDelete, field.TypeBool, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.CollectionTable,
			Columns: []string{rolepermission.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.CollectionTable,
			Columns: []string{rolepermission.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RolePermissionUpdateOne is the builder for updating a single RolePermission entity.
type RolePermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolePermissionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePermissionUpdateOne) SetUpdatedAt(v time.Time) *RolePermissionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *RolePermissionUpdateOne) SetRoleID(v uuid.UUID) *RolePermissionUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableRoleID(v *uuid.UUID) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetSection sets the "section" field.
func (_u *RolePermissionUpdateOne) SetSection(v string) *RolePermissionUpdateOne {
	_u.mutation.SetSection(v)
	return _u
}

// SetNillableSection sets the "section" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableSection(v *string) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetSection(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *RolePermissionUpdateOne) SetCollectionID(v uuid.UUID) *RolePermissionUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableCollectionID(v *uuid.UUID) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *RolePermissionUpdateOne) ClearCollectionID() *RolePermissionUpdateOne {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetCanView sets the "can_view" field.
func (_u *RolePermissionUpdateOne) SetCanView(v bool) *RolePermissionUpdateOne {
	_u.mutation.SetCanView(v)
	return _u
}

// SetNillableCanView sets the "can_view" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableCanView(v *bool) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetCanView(*v)
	}
	return _u
}

// SetCanCreate sets the "can_create" field.
func (_u *RolePermissionUpdateOne) SetCanCreate(v bool) *RolePermissionUpdateOne {
	_u.mutation.SetCanCreate(v)
	return _u
}

// SetNillableCanCreate sets the "can_create" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableCanCreate(v *bool) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetCanCreate(*v)
	}
	return _u
}

// SetCanEdit sets the "can_edit" field.
func (_u *RolePermissionUpdateOne) SetCanEdit(v bool) *RolePermissionUpdateOne {
	_u.mutation.SetCanEdit(v)
	return _u
}

// SetNillableCanEdit sets the "can_edit" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableCanEdit(v *bool) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetCanEdit(*v)
	}
	return _u
}

// SetCanDelete sets the "can_delete" field.
func (_u *RolePermissionUpdateOne) SetCanDelete(v bool) *RolePermissionUpdateOne {
	_u.mutation.SetCanDelete(v)
	return _u
}

// SetNillableCanDelete sets the "can_delete" field if the given value is not nil.
func (_u *RolePermissionUpdateOne) SetNillableCanDelete(v *bool) *RolePermissionUpdateOne {
	if v != nil {
		_u.SetCanDelete(*v)
	}
	return _u
}

// SetRole sets the "role" edge to the Role entity.
func (_u *RolePermissionUpdateOne) SetRole(v *Role) *RolePermissionUpdateOne {
	return _u.SetRoleID(v.ID)
}

// SetCollection sets the "collection" edge to the Group entity.
func (_u *RolePermissionUpdateOne) SetCollection(v *Group) *RolePermissionUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// Mutation returns the RolePermissionMutation object of the builder.
func (_u *RolePermissionUpdateOne) Mutation() *RolePermissionMutation {
	return _u.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *RolePermissionUpdateOne) ClearRole() *RolePermissionUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// ClearCollection clears the "collection" edge to the Group entity.
func (_u *RolePermissionUpdateOne) ClearCollection() *RolePermissionUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// Where appends a list predicates to the RolePermissionUpdate builder.
func (_u *RolePermissionUpdateOne) Where(ps ...predicate.RolePermission) *RolePermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RolePermissionUpdateOne) Select(field string, fields ...string) *RolePermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RolePermission entity.
func (_u *RolePermissionUpdateOne) Save(ctx context.Context) (*RolePermission, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePermissionUpdateOne) SaveX(ctx context.Context) *RolePermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RolePermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePermissionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rolepermission.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePermissionUpdateOne) check() error {
	if v, ok := _u.mutation.Section(); ok {
		if err := rolepermission.SectionValidator(v); err != nil {
			return &ValidationError{Name: "section", err: fmt.Errorf(`ent: validator failed for field "RolePermission.section": %w`, err)}
		}
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RolePermission.role"`)
	}
	return nil
}

func (_u *RolePermissionUpdateOne) sqlSave(ctx context.Context) (_node *RolePermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepermission.Table, rolepermission.Columns, sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RolePermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolepermission.FieldID)
		for _, f := range fields {
			if !rolepermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolepermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepermission.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Section(); ok {
		_spec.SetField(rolepermission.FieldSection, field.TypeString, value)
	}
	if value, ok := _u.mutation.CanView(); ok {
		_spec.SetField(rolepermission.FieldCanView, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanCreate(); ok {
		_spec.SetField(rolepermission.FieldCanCreate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanEdit(); ok {
		_spec.SetField(rolepermission.FieldCanEdit, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CanDelete(); ok {
		_spec.SetField(rolepermission.FieldCanDelete, field.TypeBool, value)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.RoleTable,
			Columns: []string{rolepermission.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.CollectionTable,
			Columns: []string{rolepermission.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   rolepermission.CollectionTable,
			Columns: []string{rolepermission.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RolePermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
