// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/schema"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/theme"
)

// ThemeUpdate is the builder for updating Theme entities.
type ThemeUpdate struct {
	config
	hooks    []Hook
	mutation *ThemeMutation
}

// Where appends a list predicates to the ThemeUpdate builder.
func (_u *ThemeUpdate) Where(ps ...predicate.Theme) *ThemeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ThemeUpdate) SetUpdatedAt(v time.Time) *ThemeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ThemeUpdate) SetName(v string) *ThemeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableName(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColors sets the "colors" field.
func (_u *ThemeUpdate) SetColors(v map[string]string) *ThemeUpdate {
	_u.mutation.SetColors(v)
	return _u
}

// SetRadius sets the "radius" field.
func (_u *ThemeUpdate) SetRadius(v string) *ThemeUpdate {
	_u.mutation.SetRadius(v)
	return _u
}

// SetNillableRadius sets the "radius" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableRadius(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetRadius(*v)
	}
	return _u
}

// ClearRadius clears the value of the "radius" field.
func (_u *ThemeUpdate) ClearRadius() *ThemeUpdate {
	_u.mutation.ClearRadius()
	return _u
}

// SetFontSans sets the "font_sans" field.
func (_u *ThemeUpdate) SetFontSans(v string) *ThemeUpdate {
	_u.mutation.SetFontSans(v)
	return _u
}

// SetNillableFontSans sets the "font_sans" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableFontSans(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetFontSans(*v)
	}
	return _u
}

// ClearFontSans clears the value of the "font_sans" field.
func (_u *ThemeUpdate) ClearFontSans() *ThemeUpdate {
	_u.mutation.ClearFontSans()
	return _u
}

// SetFontMono sets the "font_mono" field.
func (_u *ThemeUpdate) SetFontMono(v string) *ThemeUpdate {
	_u.mutation.SetFontMono(v)
	return _u
}

// SetNillableFontMono sets the "font_mono" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableFontMono(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetFontMono(*v)
	}
	return _u
}

// ClearFontMono clears the value of the "font_mono" field.
func (_u *ThemeUpdate) ClearFontMono() *ThemeUpdate {
	_u.mutation.ClearFontMono()
	return _u
}

// SetBranding sets the "branding" field.
func (_u *ThemeUpdate) SetBranding(v schema.ThemeBranding) *ThemeUpdate {
	_u.mutation.SetBranding(v)
	return _u
}

// SetNillableBranding sets the "branding" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableBranding(v *schema.ThemeBranding) *ThemeUpdate {
	if v != nil {
		_u.SetBranding(*v)
	}
	return _u
}

// SetNavLogoPath sets the "nav_logo_path" field.
func (_u *ThemeUpdate) SetNavLogoPath(v string) *ThemeUpdate {
	_u.mutation.SetNavLogoPath(v)
	return _u
}

// SetNillableNavLogoPath sets the "nav_logo_path" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableNavLogoPath(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetNavLogoPath(*v)
	}
	return _u
}

// ClearNavLogoPath clears the value of the "nav_logo_path" field.
func (_u *ThemeUpdate) ClearNavLogoPath() *ThemeUpdate {
	_u.mutation.ClearNavLogoPath()
	return _u
}

// SetSidebarLogoPath sets the "sidebar_logo_path" field.
func (_u *ThemeUpdate) SetSidebarLogoPath(v string) *ThemeUpdate {
	_u.mutation.SetSidebarLogoPath(v)
	return _u
}

// SetNillableSidebarLogoPath sets the "sidebar_logo_path" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableSidebarLogoPath(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetSidebarLogoPath(*v)
	}
	return _u
}

// ClearSidebarLogoPath clears the value of the "sidebar_logo_path" field.
func (_u *ThemeUpdate) ClearSidebarLogoPath() *ThemeUpdate {
	_u.mutation.ClearSidebarLogoPath()
	return _u
}

// SetLoginIconPath sets the "login_icon_path" field.
func (_u *ThemeUpdate) SetLoginIconPath(v string) *ThemeUpdate {
	_u.mutation.SetLoginIconPath(v)
	return _u
}

// SetNillableLoginIconPath sets the "login_icon_path" field if the given value is not nil.
func (_u *ThemeUpdate) SetNillableLoginIconPath(v *string) *ThemeUpdate {
	if v != nil {
		_u.SetLoginIconPath(*v)
	}
	return _u
}

// ClearLoginIconPath clears the value of the "login_icon_path" field.
func (_u *ThemeUpdate) ClearLoginIconPath() *ThemeUpdate {
	_u.mutation.ClearLoginIconPath()
	return _u
}

// Mutation returns the ThemeMutation object of the builder.
func (_u *ThemeUpdate) Mutation() *ThemeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ThemeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThemeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ThemeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThemeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ThemeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theme.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThemeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ThemeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theme.Table, theme.Columns, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Colors(); ok {
		_spec.SetField(theme.FieldColors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Radius(); ok {
		_spec.SetField(theme.FieldRadius, field.TypeString, value)
	}
	if _u.mutation.RadiusCleared() {
		_spec.ClearField(theme.FieldRadius, field.TypeString)
	}
	if value, ok := _u.mutation.FontSans(); ok {
		_spec.SetField(theme.FieldFontSans, field.TypeString, value)
	}
	if _u.mutation.FontSansCleared() {
		_spec.ClearField(theme.FieldFontSans, field.TypeString)
	}
	if value, ok := _u.mutation.FontMono(); ok {
		_spec.SetField(theme.FieldFontMono, field.TypeString, value)
	}
	if _u.mutation.FontMonoCleared() {
		_spec.ClearField(theme.FieldFontMono, field.TypeString)
	}
	if value, ok := _u.mutation.Branding(); ok {
		_spec.SetField(theme.FieldBranding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.NavLogoPath(); ok {
		_spec.SetField(theme.FieldNavLogoPath, field.TypeString, value)
	}
	if _u.mutation.NavLogoPathCleared() {
		_spec.ClearField(theme.FieldNavLogoPath, field.TypeString)
	}
	if value, ok := _u.mutation.SidebarLogoPath(); ok {
		_spec.SetField(theme.FieldSidebarLogoPath, field.TypeString, value)
	}
	if _u.mutation.SidebarLogoPathCleared() {
		_spec.ClearField(theme.FieldSidebarLogoPath, field.TypeString)
	}
	if value, ok := _u.mutation.LoginIconPath(); ok {
		_spec.SetField(theme.FieldLoginIconPath, field.TypeString, value)
	}
	if _u.mutation.LoginIconPathCleared() {
		_spec.ClearField(theme.FieldLoginIconPath, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ThemeUpdateOne is the builder for updating a single Theme entity.
type ThemeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThemeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ThemeUpdateOne) SetUpdatedAt(v time.Time) *ThemeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ThemeUpdateOne) SetName(v string) *ThemeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableName(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetColors sets the "colors" field.
func (_u *ThemeUpdateOne) SetColors(v map[string]string) *ThemeUpdateOne {
	_u.mutation.SetColors(v)
	return _u
}

// SetRadius sets the "radius" field.
func (_u *ThemeUpdateOne) SetRadius(v string) *ThemeUpdateOne {
	_u.mutation.SetRadius(v)
	return _u
}

// SetNillableRadius sets the "radius" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableRadius(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetRadius(*v)
	}
	return _u
}

// ClearRadius clears the value of the "radius" field.
func (_u *ThemeUpdateOne) ClearRadius() *ThemeUpdateOne {
	_u.mutation.ClearRadius()
	return _u
}

// SetFontSans sets the "font_sans" field.
func (_u *ThemeUpdateOne) SetFontSans(v string) *ThemeUpdateOne {
	_u.mutation.SetFontSans(v)
	return _u
}

// SetNillableFontSans sets the "font_sans" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableFontSans(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetFontSans(*v)
	}
	return _u
}

// ClearFontSans clears the value of the "font_sans" field.
func (_u *ThemeUpdateOne) ClearFontSans() *ThemeUpdateOne {
	_u.mutation.ClearFontSans()
	return _u
}

// SetFontMono sets the "font_mono" field.
func (_u *ThemeUpdateOne) SetFontMono(v string) *ThemeUpdateOne {
	_u.mutation.SetFontMono(v)
	return _u
}

// SetNillableFontMono sets the "font_mono" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableFontMono(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetFontMono(*v)
	}
	return _u
}

// ClearFontMono clears the value of the "font_mono" field.
func (_u *ThemeUpdateOne) ClearFontMono() *ThemeUpdateOne {
	_u.mutation.ClearFontMono()
	return _u
}

// SetBranding sets the "branding" field.
func (_u *ThemeUpdateOne) SetBranding(v schema.ThemeBranding) *ThemeUpdateOne {
	_u.mutation.SetBranding(v)
	return _u
}

// SetNillableBranding sets the "branding" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableBranding(v *schema.ThemeBranding) *ThemeUpdateOne {
	if v != nil {
		_u.SetBranding(*v)
	}
	return _u
}

// SetNavLogoPath sets the "nav_logo_path" field.
func (_u *ThemeUpdateOne) SetNavLogoPath(v string) *ThemeUpdateOne {
	_u.mutation.SetNavLogoPath(v)
	return _u
}

// SetNillableNavLogoPath sets the "nav_logo_path" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableNavLogoPath(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetNavLogoPath(*v)
	}
	return _u
}

// ClearNavLogoPath clears the value of the "nav_logo_path" field.
func (_u *ThemeUpdateOne) ClearNavLogoPath() *ThemeUpdateOne {
	_u.mutation.ClearNavLogoPath()
	return _u
}

// SetSidebarLogoPath sets the "sidebar_logo_path" field.
func (_u *ThemeUpdateOne) SetSidebarLogoPath(v string) *ThemeUpdateOne {
	_u.mutation.SetSidebarLogoPath(v)
	return _u
}

// SetNillableSidebarLogoPath sets the "sidebar_logo_path" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableSidebarLogoPath(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetSidebarLogoPath(*v)
	}
	return _u
}

// ClearSidebarLogoPath clears the value of the "sidebar_logo_path" field.
func (_u *ThemeUpdateOne) ClearSidebarLogoPath() *ThemeUpdateOne {
	_u.mutation.ClearSidebarLogoPath()
	return _u
}

// SetLoginIconPath sets the "login_icon_path" field.
func (_u *ThemeUpdateOne) SetLoginIconPath(v string) *ThemeUpdateOne {
	_u.mutation.SetLoginIconPath(v)
	return _u
}

// SetNillableLoginIconPath sets the "login_icon_path" field if the given value is not nil.
func (_u *ThemeUpdateOne) SetNillableLoginIconPath(v *string) *ThemeUpdateOne {
	if v != nil {
		_u.SetLoginIconPath(*v)
	}
	return _u
}

// ClearLoginIconPath clears the value of the "login_icon_path" field.
func (_u *ThemeUpdateOne) ClearLoginIconPath() *ThemeUpdateOne {
	_u.mutation.ClearLoginIconPath()
	return _u
}

// Mutation returns the ThemeMutation object of the builder.
func (_u *ThemeUpdateOne) Mutation() *ThemeMutation {
	return _u.mutation
}

// Where appends a list predicates to the ThemeUpdate builder.
func (_u *ThemeUpdateOne) Where(ps ...predicate.Theme) *ThemeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ThemeUpdateOne) Select(field string, fields ...string) *ThemeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Theme entity.
func (_u *ThemeUpdateOne) Save(ctx context.Context) (*Theme, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ThemeUpdateOne) SaveX(ctx context.Context) *Theme {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ThemeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ThemeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ThemeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := theme.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ThemeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ThemeUpdateOne) sqlSave(ctx context.Context) (_node *Theme, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(theme.Table, theme.Columns, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Theme.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, theme.FieldID)
		for _, f := range fields {
			if !theme.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != theme.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Colors(); ok {
		_spec.SetField(theme.FieldColors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Radius(); ok {
		_spec.SetField(theme.FieldRadius, field.TypeString, value)
	}
	if _u.mutation.RadiusCleared() {
		_spec.ClearField(theme.FieldRadius, field.TypeString)
	}
	if value, ok := _u.mutation.FontSans(); ok {
		_spec.SetField(theme.FieldFontSans, field.TypeString, value)
	}
	if _u.mutation.FontSansCleared() {
		_spec.ClearField(theme.FieldFontSans, field.TypeString)
	}
	if value, ok := _u.mutation.FontMono(); ok {
		_spec.SetField(theme.FieldFontMono, field.TypeString, value)
	}
	if _u.mutation.FontMonoCleared() {
		_spec.ClearField(theme.FieldFontMono, field.TypeString)
	}
	if value, ok := _u.mutation.Branding(); ok {
		_spec.SetField(theme.FieldBranding, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.NavLogoPath(); ok {
		_spec.SetField(theme.FieldNavLogoPath, field.TypeString, value)
	}
	if _u.mutation.NavLogoPathCleared() {
		_spec.ClearField(theme.FieldNavLogoPath, field.TypeString)
	}
	if value, ok := _u.mutation.SidebarLogoPath(); ok {
		_spec.SetField(theme.FieldSidebarLogoPath, field.TypeString, value)
	}
	if _u.mutation.SidebarLogoPathCleared() {
		_spec.ClearField(theme.FieldSidebarLogoPath, field.TypeString)
	}
	if value, ok := _u.mutation.LoginIconPath(); ok {
		_spec.SetField(theme.FieldLoginIconPath, field.TypeString, value)
	}
	if _u.mutation.LoginIconPathCleared() {
		_spec.ClearField(theme.FieldLoginIconPath, field.TypeString)
	}
	_node = &Theme{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{theme.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
