// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/schema"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/theme"
)

// ThemeCreate is the builder for creating a Theme entity.
type ThemeCreate struct {
	config
	mutation *ThemeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ThemeCreate) SetCreatedAt(v time.Time) *ThemeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableCreatedAt(v *time.Time) *ThemeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ThemeCreate) SetUpdatedAt(v time.Time) *ThemeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableUpdatedAt(v *time.Time) *ThemeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ThemeCreate) SetName(v string) *ThemeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetColors sets the "colors" field.
func (_c *ThemeCreate) SetColors(v map[string]string) *ThemeCreate {
	_c.mutation.SetColors(v)
	return _c
}

// SetRadius sets the "radius" field.
func (_c *ThemeCreate) SetRadius(v string) *ThemeCreate {
	_c.mutation.SetRadius(v)
	return _c
}

// SetNillableRadius sets the "radius" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableRadius(v *string) *ThemeCreate {
	if v != nil {
		_c.SetRadius(*v)
	}
	return _c
}

// SetFontSans sets the "font_sans" field.
func (_c *ThemeCreate) SetFontSans(v string) *ThemeCreate {
	_c.mutation.SetFontSans(v)
	return _c
}

// SetNillableFontSans sets the "font_sans" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableFontSans(v *string) *ThemeCreate {
	if v != nil {
		_c.SetFontSans(*v)
	}
	return _c
}

// SetFontMono sets the "font_mono" field.
func (_c *ThemeCreate) SetFontMono(v string) *ThemeCreate {
	_c.mutation.SetFontMono(v)
	return _c
}

// SetNillableFontMono sets the "font_mono" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableFontMono(v *string) *ThemeCreate {
	if v != nil {
		_c.SetFontMono(*v)
	}
	return _c
}

// SetBranding sets the "branding" field.
func (_c *ThemeCreate) SetBranding(v schema.ThemeBranding) *ThemeCreate {
	_c.mutation.SetBranding(v)
	return _c
}

// SetNavLogoPath sets the "nav_logo_path" field.
func (_c *ThemeCreate) SetNavLogoPath(v string) *ThemeCreate {
	_c.mutation.SetNavLogoPath(v)
	return _c
}

// SetNillableNavLogoPath sets the "nav_logo_path" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableNavLogoPath(v *string) *ThemeCreate {
	if v != nil {
		_c.SetNavLogoPath(*v)
	}
	return _c
}

// SetSidebarLogoPath sets the "sidebar_logo_path" field.
func (_c *ThemeCreate) SetSidebarLogoPath(v string) *ThemeCreate {
	_c.mutation.SetSidebarLogoPath(v)
	return _c
}

// SetNillableSidebarLogoPath sets the "sidebar_logo_path" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableSidebarLogoPath(v *string) *ThemeCreate {
	if v != nil {
		_c.SetSidebarLogoPath(*v)
	}
	return _c
}

// SetLoginIconPath sets the "login_icon_path" field.
func (_c *ThemeCreate) SetLoginIconPath(v string) *ThemeCreate {
	_c.mutation.SetLoginIconPath(v)
	return _c
}

// SetNillableLoginIconPath sets the "login_icon_path" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableLoginIconPath(v *string) *ThemeCreate {
	if v != nil {
		_c.SetLoginIconPath(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ThemeCreate) SetID(v uuid.UUID) *ThemeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ThemeCreate) SetNillableID(v *uuid.UUID) *ThemeCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ThemeMutation object of the builder.
func (_c *ThemeCreate) Mutation() *ThemeMutation {
	return _c.mutation
}

// Save creates the Theme in the database.
func (_c *ThemeCreate) Save(ctx context.Context) (*Theme, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ThemeCreate) SaveX(ctx context.Context) *Theme {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThemeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThemeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ThemeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := theme.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := theme.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Radius(); !ok {
		v := theme.DefaultRadius
		_c.mutation.SetRadius(v)
	}
	if _, ok := _c.mutation.FontSans(); !ok {
		v := theme.DefaultFontSans
		_c.mutation.SetFontSans(v)
	}
	if _, ok := _c.mutation.FontMono(); !ok {
		v := theme.DefaultFontMono
		_c.mutation.SetFontMono(v)
	}
	if _, ok := _c.mutation.NavLogoPath(); !ok {
		v := theme.DefaultNavLogoPath
		_c.mutation.SetNavLogoPath(v)
	}
	if _, ok := _c.mutation.SidebarLogoPath(); !ok {
		v := theme.DefaultSidebarLogoPath
		_c.mutation.SetSidebarLogoPath(v)
	}
	if _, ok := _c.mutation.LoginIconPath(); !ok {
		v := theme.DefaultLoginIconPath
		_c.mutation.SetLoginIconPath(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := theme.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ThemeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Theme.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Theme.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Theme.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := theme.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Theme.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Colors(); !ok {
		return &ValidationError{Name: "colors", err: errors.New(`ent: missing required field "Theme.colors"`)}
	}
	if _, ok := _c.mutation.Branding(); !ok {
		return &ValidationError{Name: "branding", err: errors.New(`ent: missing required field "Theme.branding"`)}
	}
	return nil
}

func (_c *ThemeCreate) sqlSave(ctx context.Context) (*Theme, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ThemeCreate) createSpec() (*Theme, *sqlgraph.CreateSpec) {
	var (
		_node = &Theme{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(theme.Table, sqlgraph.NewFieldSpec(theme.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(theme.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(theme.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(theme.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Colors(); ok {
		_spec.SetField(theme.FieldColors, field.TypeJSON, value)
		_node.Colors = value
	}
	if value, ok := _c.mutation.Radius(); ok {
		_spec.SetField(theme.FieldRadius, field.TypeString, value)
		_node.Radius = value
	}
	if value, ok := _c.mutation.FontSans(); ok {
		_spec.SetField(theme.FieldFontSans, field.TypeString, value)
		_node.FontSans = value
	}
	if value, ok := _c.mutation.FontMono(); ok {
		_spec.SetField(theme.FieldFontMono, field.TypeString, value)
		_node.FontMono = value
	}
	if value, ok := _c.mutation.Branding(); ok {
		_spec.SetField(theme.FieldBranding, field.TypeJSON, value)
		_node.Branding = value
	}
	if value, ok := _c.mutation.NavLogoPath(); ok {
		_spec.SetField(theme.FieldNavLogoPath, field.TypeString, value)
		_node.NavLogoPath = value
	}
	if value, ok := _c.mutation.SidebarLogoPath(); ok {
		_spec.SetField(theme.FieldSidebarLogoPath, field.TypeString, value)
		_node.SidebarLogoPath = value
	}
	if value, ok := _c.mutation.LoginIconPath(); ok {
		_spec.SetField(theme.FieldLoginIconPath, field.TypeString, value)
		_node.LoginIconPath = value
	}
	return _node, _spec
}

// ThemeCreateBulk is the builder for creating many Theme entities in bulk.
type ThemeCreateBulk struct {
	config
	err      error
	builders []*ThemeCreate
}

// Save creates the Theme entities in the database.
func (_c *ThemeCreateBulk) Save(ctx context.Context) ([]*Theme, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Theme, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ThemeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ThemeCreateBulk) SaveX(ctx context.Context) []*Theme {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ThemeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ThemeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
