// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/schema"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/theme"
)

// Theme is the model entity for the Theme schema.
type Theme struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Colors holds the value of the "colors" field.
	Colors map[string]string `json:"colors,omitempty"`
	// Radius holds the value of the "radius" field.
	Radius string `json:"radius,omitempty"`
	// FontSans holds the value of the "font_sans" field.
	FontSans string `json:"font_sans,omitempty"`
	// FontMono holds the value of the "font_mono" field.
	FontMono string `json:"font_mono,omitempty"`
	// Branding holds the value of the "branding" field.
	Branding schema.ThemeBranding `json:"branding,omitempty"`
	// NavLogoPath holds the value of the "nav_logo_path" field.
	NavLogoPath string `json:"nav_logo_path,omitempty"`
	// SidebarLogoPath holds the value of the "sidebar_logo_path" field.
	SidebarLogoPath string `json:"sidebar_logo_path,omitempty"`
	// LoginIconPath holds the value of the "login_icon_path" field.
	LoginIconPath string `json:"login_icon_path,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Theme) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case theme.FieldColors, theme.FieldBranding:
			values[i] = new([]byte)
		case theme.FieldName, theme.FieldRadius, theme.FieldFontSans, theme.FieldFontMono, theme.FieldNavLogoPath, theme.FieldSidebarLogoPath, theme.FieldLoginIconPath:
			values[i] = new(sql.NullString)
		case theme.FieldCreatedAt, theme.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case theme.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Theme fields.
func (_m *Theme) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case theme.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case theme.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case theme.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case theme.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case theme.FieldColors:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field colors", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Colors); err != nil {
					return fmt.Errorf("unmarshal field colors: %w", err)
				}
			}
		case theme.FieldRadius:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field radius", values[i])
			} else if value.Valid {
				_m.Radius = value.String
			}
		case theme.FieldFontSans:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field font_sans", values[i])
			} else if value.Valid {
				_m.FontSans = value.String
			}
		case theme.FieldFontMono:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field font_mono", values[i])
			} else if value.Valid {
				_m.FontMono = value.String
			}
		case theme.FieldBranding:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field branding", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Branding); err != nil {
					return fmt.Errorf("unmarshal field branding: %w", err)
				}
			}
		case theme.FieldNavLogoPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field nav_logo_path", values[i])
			} else if value.Valid {
				_m.NavLogoPath = value.String
			}
		case theme.FieldSidebarLogoPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sidebar_logo_path", values[i])
			} else if value.Valid {
				_m.SidebarLogoPath = value.String
			}
		case theme.FieldLoginIconPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field login_icon_path", values[i])
			} else if value.Valid {
				_m.LoginIconPath = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Theme.
// This includes values selected through modifiers, order, etc.
func (_m *Theme) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Theme.
// Note that you need to call Theme.Unwrap() before calling this method if this Theme
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Theme) Update() *ThemeUpdateOne {
	return NewThemeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Theme entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Theme) Unwrap() *Theme {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Theme is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Theme) String() string {
	var builder strings.Builder
	builder.WriteString("Theme(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("colors=")
	builder.WriteString(fmt.Sprintf("%v", _m.Colors))
	builder.WriteString(", ")
	builder.WriteString("radius=")
	builder.WriteString(_m.Radius)
	builder.WriteString(", ")
	builder.WriteString("font_sans=")
	builder.WriteString(_m.FontSans)
	builder.WriteString(", ")
	builder.WriteString("font_mono=")
	builder.WriteString(_m.FontMono)
	builder.WriteString(", ")
	builder.WriteString("branding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Branding))
	builder.WriteString(", ")
	builder.WriteString("nav_logo_path=")
	builder.WriteString(_m.NavLogoPath)
	builder.WriteString(", ")
	builder.WriteString("sidebar_logo_path=")
	builder.WriteString(_m.SidebarLogoPath)
	builder.WriteString(", ")
	builder.WriteString("login_icon_path=")
	builder.WriteString(_m.LoginIconPath)
	builder.WriteByte(')')
	return builder.String()
}

// Themes is a parsable slice of Theme.
type Themes []*Theme
