// Code generated by ent, DO NOT EDIT.

package rolepermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the rolepermission type in the database.
	Label = "role_permission"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRoleID holds the string denoting the role_id field in the database.
	FieldRoleID = "role_id"
	// FieldSection holds the string denoting the section field in the database.
	FieldSection = "section"
	// FieldCollectionID holds the string denoting the collection_id field in the database.
	FieldCollectionID = "collection_id"
	// FieldCanView holds the string denoting the can_view field in the database.
	FieldCanView = "can_view"
	// FieldCanCreate holds the string denoting the can_create field in the database.
	FieldCanCreate = "can_create"
	// FieldCanEdit holds the string denoting the can_edit field in the database.
	FieldCanEdit = "can_edit"
	// FieldCanDelete holds the string denoting the can_delete field in the database.
	FieldCanDelete = "can_delete"
	// EdgeRole holds the string denoting the role edge name in mutations.
	EdgeRole = "role"
	// EdgeCollection holds the string denoting the collection edge name in mutations.
	EdgeCollection = "collection"
	// Table holds the table name of the rolepermission in the database.
	Table = "role_permissions"
	// RoleTable is the table that holds the role relation/edge.
	RoleTable = "role_permissions"
	// RoleInverseTable is the table name for the Role entity.
	// It exists in this package in order to avoid circular dependency with the "role" package.
	RoleInverseTable = "roles"
	// RoleColumn is the table column denoting the role relation/edge.
	RoleColumn = "role_id"
	// CollectionTable is the table that holds the collection relation/edge.
	CollectionTable = "role_permissions"
	// CollectionInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	CollectionInverseTable = "groups"
	// CollectionColumn is the table column denoting the collection relation/edge.
	CollectionColumn = "collection_id"
)

// Columns holds all SQL columns for rolepermission fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRoleID,
	FieldSection,
	FieldCollectionID,
	FieldCanView,
	FieldCanCreate,
	FieldCanEdit,
	FieldCanDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// SectionValidator is a validator for the "section" field. It is called by the builders before save.
	SectionValidator func(string) error
	// DefaultCanView holds the default value on creation for the "can_view" field.
	DefaultCanView bool
	// DefaultCanCreate holds the default value on creation for the "can_create" field.
	DefaultCanCreate bool
	// DefaultCanEdit holds the default value on creation for the "can_edit" field.
	DefaultCanEdit bool
	// DefaultCanDelete holds the default value on creation for the "can_delete" field.
	DefaultCanDelete bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the RolePermission queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRoleID orders the results by the role_id field.
func ByRoleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoleID, opts...).ToFunc()
}

// BySection orders the results by the section field.
func BySection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSection, opts...).ToFunc()
}

// ByCollectionID orders the results by the collection_id field.
func ByCollectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectionID, opts...).ToFunc()
}

// ByCanView orders the results by the can_view field.
func ByCanView(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanView, opts...).ToFunc()
}

// ByCanCreate orders the results by the can_create field.
func ByCanCreate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanCreate, opts...).ToFunc()
}

// ByCanEdit orders the results by the can_edit field.
func ByCanEdit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanEdit, opts...).ToFunc()
}

// ByCanDelete orders the results by the can_delete field.
func ByCanDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanDelete, opts...).ToFunc()
}

// ByRoleField orders the results by role field.
func ByRoleField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoleStep(), sql.OrderByField(field, opts...))
	}
}

// ByCollectionField orders the results by collection field.
func ByCollectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCollectionStep(), sql.OrderByField(field, opts...))
	}
}
func newRoleStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoleInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
	)
}
func newCollectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CollectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CollectionTable, CollectionColumn),
	)
}
