// Code generated by ent, DO NOT EDIT.

package rolepermission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldRoleID, v))
}

// Section applies equality check predicate on the "section" field. It's identical to SectionEQ.
func Section(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldSection, v))
}

// CollectionID applies equality check predicate on the "collection_id" field. It's identical to CollectionIDEQ.
func CollectionID(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCollectionID, v))
}

// CanView applies equality check predicate on the "can_view" field. It's identical to CanViewEQ.
func CanView(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanView, v))
}

// CanCreate applies equality check predicate on the "can_create" field. It's identical to CanCreateEQ.
func CanCreate(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanCreate, v))
}

// CanEdit applies equality check predicate on the "can_edit" field. It's identical to CanEditEQ.
func CanEdit(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanEdit, v))
}

// CanDelete applies equality check predicate on the "can_delete" field. It's identical to CanDeleteEQ.
func CanDelete(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanDelete, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldUpdatedAt, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldRoleID, vs...))
}

// SectionEQ applies the EQ predicate on the "section" field.
func SectionEQ(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldSection, v))
}

// SectionNEQ applies the NEQ predicate on the "section" field.
func SectionNEQ(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldSection, v))
}

// SectionIn applies the In predicate on the "section" field.
func SectionIn(vs ...string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldSection, vs...))
}

// SectionNotIn applies the NotIn predicate on the "section" field.
func SectionNotIn(vs ...string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldSection, vs...))
}

// SectionGT applies the GT predicate on the "section" field.
func SectionGT(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGT(FieldSection, v))
}

// SectionGTE applies the GTE predicate on the "section" field.
func SectionGTE(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldGTE(FieldSection, v))
}

// SectionLT applies the LT predicate on the "section" field.
func SectionLT(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLT(FieldSection, v))
}

// SectionLTE applies the LTE predicate on the "section" field.
func SectionLTE(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldLTE(FieldSection, v))
}

// SectionContains applies the Contains predicate on the "section" field.
func SectionContains(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldContains(FieldSection, v))
}

// SectionHasPrefix applies the HasPrefix predicate on the "section" field.
func SectionHasPrefix(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldHasPrefix(FieldSection, v))
}

// SectionHasSuffix applies the HasSuffix predicate on the "section" field.
func SectionHasSuffix(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldHasSuffix(FieldSection, v))
}

// SectionEqualFold applies the EqualFold predicate on the "section" field.
func SectionEqualFold(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEqualFold(FieldSection, v))
}

// SectionContainsFold applies the ContainsFold predicate on the "section" field.
func SectionContainsFold(v string) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldContainsFold(FieldSection, v))
}

// CollectionIDEQ applies the EQ predicate on the "collection_id" field.
func CollectionIDEQ(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCollectionID, v))
}

// CollectionIDNEQ applies the NEQ predicate on the "collection_id" field.
func CollectionIDNEQ(v uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCollectionID, v))
}

// CollectionIDIn applies the In predicate on the "collection_id" field.
func CollectionIDIn(vs ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIn(FieldCollectionID, vs...))
}

// CollectionIDNotIn applies the NotIn predicate on the "collection_id" field.
func CollectionIDNotIn(vs ...uuid.UUID) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotIn(FieldCollectionID, vs...))
}

// CollectionIDIsNil applies the IsNil predicate on the "collection_id" field.
func CollectionIDIsNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldIsNull(FieldCollectionID))
}

// CollectionIDNotNil applies the NotNil predicate on the "collection_id" field.
func CollectionIDNotNil() predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNotNull(FieldCollectionID))
}

// CanViewEQ applies the EQ predicate on the "can_view" field.
func CanViewEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanView, v))
}

// CanViewNEQ applies the NEQ predicate on the "can_view" field.
func CanViewNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanView, v))
}

// CanCreateEQ applies the EQ predicate on the "can_create" field.
func CanCreateEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanCreate, v))
}

// CanCreateNEQ applies the NEQ predicate on the "can_create" field.
func CanCreateNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanCreate, v))
}

// CanEditEQ applies the EQ predicate on the "can_edit" field.
func CanEditEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanEdit, v))
}

// CanEditNEQ applies the NEQ predicate on the "can_edit" field.
func CanEditNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanEdit, v))
}

// CanDeleteEQ applies the EQ predicate on the "can_delete" field.
func CanDeleteEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldEQ(FieldCanDelete, v))
}

// CanDeleteNEQ applies the NEQ predicate on the "can_delete" field.
func CanDeleteNEQ(v bool) predicate.RolePermission {
	return predicate.RolePermission(sql.FieldNEQ(FieldCanDelete, v))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCollection applies the HasEdge predicate on the "collection" edge.
func HasCollection() predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CollectionTable, CollectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCollectionWith applies the HasEdge predicate on the "collection" edge with a given conditions (other predicates).
func HasCollectionWith(preds ...predicate.Group) predicate.RolePermission {
	return predicate.RolePermission(func(s *sql.Selector) {
		step := newCollectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RolePermission) predicate.RolePermission {
	return predicate.RolePermission(sql.NotPredicates(p))
}
