// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// APIKey is the predicate function for apikey builders.
type APIKey func(*sql.Selector)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// AuthRoles is the predicate function for authroles builders.
type AuthRoles func(*sql.Selector)

// AuthTokens is the predicate function for authtokens builders.
type AuthTokens func(*sql.Selector)

// Entity is the predicate function for entity builders.
type Entity func(*sql.Selector)

// EntityField is the predicate function for entityfield builders.
type EntityField func(*sql.Selector)

// EntityTemplate is the predicate function for entitytemplate builders.
type EntityTemplate func(*sql.Selector)

// EntityType is the predicate function for entitytype builders.
type EntityType func(*sql.Selector)

// Export is the predicate function for export builders.
type Export func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// MaintenanceEntry is the predicate function for maintenanceentry builders.
type MaintenanceEntry func(*sql.Selector)

// Notifier is the predicate function for notifier builders.
type Notifier func(*sql.Selector)

// PasswordResetTokens is the predicate function for passwordresettokens builders.
type PasswordResetTokens func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// SiteSetting is the predicate function for sitesetting builders.
type SiteSetting func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// TemplateField is the predicate function for templatefield builders.
type TemplateField func(*sql.Selector)

// Theme is the predicate function for theme builders.
type Theme func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
