// Code generated by ent, DO NOT EDIT.

package theme

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the theme type in the database.
	Label = "theme"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldColors holds the string denoting the colors field in the database.
	FieldColors = "colors"
	// FieldRadius holds the string denoting the radius field in the database.
	FieldRadius = "radius"
	// FieldFontSans holds the string denoting the font_sans field in the database.
	FieldFontSans = "font_sans"
	// FieldFontMono holds the string denoting the font_mono field in the database.
	FieldFontMono = "font_mono"
	// FieldBranding holds the string denoting the branding field in the database.
	FieldBranding = "branding"
	// FieldNavLogoPath holds the string denoting the nav_logo_path field in the database.
	FieldNavLogoPath = "nav_logo_path"
	// FieldSidebarLogoPath holds the string denoting the sidebar_logo_path field in the database.
	FieldSidebarLogoPath = "sidebar_logo_path"
	// FieldLoginIconPath holds the string denoting the login_icon_path field in the database.
	FieldLoginIconPath = "login_icon_path"
	// Table holds the table name of the theme in the database.
	Table = "themes"
)

// Columns holds all SQL columns for theme fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldColors,
	FieldRadius,
	FieldFontSans,
	FieldFontMono,
	FieldBranding,
	FieldNavLogoPath,
	FieldSidebarLogoPath,
	FieldLoginIconPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultRadius holds the default value on creation for the "radius" field.
	DefaultRadius string
	// DefaultFontSans holds the default value on creation for the "font_sans" field.
	DefaultFontSans string
	// DefaultFontMono holds the default value on creation for the "font_mono" field.
	DefaultFontMono string
	// DefaultNavLogoPath holds the default value on creation for the "nav_logo_path" field.
	DefaultNavLogoPath string
	// DefaultSidebarLogoPath holds the default value on creation for the "sidebar_logo_path" field.
	DefaultSidebarLogoPath string
	// DefaultLoginIconPath holds the default value on creation for the "login_icon_path" field.
	DefaultLoginIconPath string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Theme queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRadius orders the results by the radius field.
func ByRadius(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRadius, opts...).ToFunc()
}

// ByFontSans orders the results by the font_sans field.
func ByFontSans(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontSans, opts...).ToFunc()
}

// ByFontMono orders the results by the font_mono field.
func ByFontMono(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFontMono, opts...).ToFunc()
}

// ByNavLogoPath orders the results by the nav_logo_path field.
func ByNavLogoPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNavLogoPath, opts...).ToFunc()
}

// BySidebarLogoPath orders the results by the sidebar_logo_path field.
func BySidebarLogoPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSidebarLogoPath, opts...).ToFunc()
}

// ByLoginIconPath orders the results by the login_icon_path field.
func ByLoginIconPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginIconPath, opts...).ToFunc()
}
