// Code generated by ent, DO NOT EDIT.

package theme

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldName, v))
}

// Radius applies equality check predicate on the "radius" field. It's identical to RadiusEQ.
func Radius(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldRadius, v))
}

// FontSans applies equality check predicate on the "font_sans" field. It's identical to FontSansEQ.
func FontSans(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldFontSans, v))
}

// FontMono applies equality check predicate on the "font_mono" field. It's identical to FontMonoEQ.
func FontMono(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldFontMono, v))
}

// NavLogoPath applies equality check predicate on the "nav_logo_path" field. It's identical to NavLogoPathEQ.
func NavLogoPath(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldNavLogoPath, v))
}

// SidebarLogoPath applies equality check predicate on the "sidebar_logo_path" field. It's identical to SidebarLogoPathEQ.
func SidebarLogoPath(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldSidebarLogoPath, v))
}

// LoginIconPath applies equality check predicate on the "login_icon_path" field. It's identical to LoginIconPathEQ.
func LoginIconPath(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldLoginIconPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldName, v))
}

// RadiusEQ applies the EQ predicate on the "radius" field.
func RadiusEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldRadius, v))
}

// RadiusNEQ applies the NEQ predicate on the "radius" field.
func RadiusNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldRadius, v))
}

// RadiusIn applies the In predicate on the "radius" field.
func RadiusIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldRadius, vs...))
}

// RadiusNotIn applies the NotIn predicate on the "radius" field.
func RadiusNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldRadius, vs...))
}

// RadiusGT applies the GT predicate on the "radius" field.
func RadiusGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldRadius, v))
}

// RadiusGTE applies the GTE predicate on the "radius" field.
func RadiusGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldRadius, v))
}

// RadiusLT applies the LT predicate on the "radius" field.
func RadiusLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldRadius, v))
}

// RadiusLTE applies the LTE predicate on the "radius" field.
func RadiusLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldRadius, v))
}

// RadiusContains applies the Contains predicate on the "radius" field.
func RadiusContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldRadius, v))
}

// RadiusHasPrefix applies the HasPrefix predicate on the "radius" field.
func RadiusHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldRadius, v))
}

// RadiusHasSuffix applies the HasSuffix predicate on the "radius" field.
func RadiusHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldRadius, v))
}

// RadiusIsNil applies the IsNil predicate on the "radius" field.
func RadiusIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldRadius))
}

// RadiusNotNil applies the NotNil predicate on the "radius" field.
func RadiusNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldRadius))
}

// RadiusEqualFold applies the EqualFold predicate on the "radius" field.
func RadiusEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldRadius, v))
}

// RadiusContainsFold applies the ContainsFold predicate on the "radius" field.
func RadiusContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldRadius, v))
}

// FontSansEQ applies the EQ predicate on the "font_sans" field.
func FontSansEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldFontSans, v))
}

// FontSansNEQ applies the NEQ predicate on the "font_sans" field.
func FontSansNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldFontSans, v))
}

// FontSansIn applies the In predicate on the "font_sans" field.
func FontSansIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldFontSans, vs...))
}

// FontSansNotIn applies the NotIn predicate on the "font_sans" field.
func FontSansNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldFontSans, vs...))
}

// FontSansGT applies the GT predicate on the "font_sans" field.
func FontSansGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldFontSans, v))
}

// FontSansGTE applies the GTE predicate on the "font_sans" field.
func FontSansGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldFontSans, v))
}

// FontSansLT applies the LT predicate on the "font_sans" field.
func FontSansLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldFontSans, v))
}

// FontSansLTE applies the LTE predicate on the "font_sans" field.
func FontSansLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldFontSans, v))
}

// FontSansContains applies the Contains predicate on the "font_sans" field.
func FontSansContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldFontSans, v))
}

// FontSansHasPrefix applies the HasPrefix predicate on the "font_sans" field.
func FontSansHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldFontSans, v))
}

// FontSansHasSuffix applies the HasSuffix predicate on the "font_sans" field.
func FontSansHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldFontSans, v))
}

// FontSansIsNil applies the IsNil predicate on the "font_sans" field.
func FontSansIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldFontSans))
}

// FontSansNotNil applies the NotNil predicate on the "font_sans" field.
func FontSansNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldFontSans))
}

// FontSansEqualFold applies the EqualFold predicate on the "font_sans" field.
func FontSansEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldFontSans, v))
}

// FontSansContainsFold applies the ContainsFold predicate on the "font_sans" field.
func FontSansContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldFontSans, v))
}

// FontMonoEQ applies the EQ predicate on the "font_mono" field.
func FontMonoEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldFontMono, v))
}

// FontMonoNEQ applies the NEQ predicate on the "font_mono" field.
func FontMonoNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldFontMono, v))
}

// FontMonoIn applies the In predicate on the "font_mono" field.
func FontMonoIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldFontMono, vs...))
}

// FontMonoNotIn applies the NotIn predicate on the "font_mono" field.
func FontMonoNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldFontMono, vs...))
}

// FontMonoGT applies the GT predicate on the "font_mono" field.
func FontMonoGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldFontMono, v))
}

// FontMonoGTE applies the GTE predicate on the "font_mono" field.
func FontMonoGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldFontMono, v))
}

// FontMonoLT applies the LT predicate on the "font_mono" field.
func FontMonoLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldFontMono, v))
}

// FontMonoLTE applies the LTE predicate on the "font_mono" field.
func FontMonoLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldFontMono, v))
}

// FontMonoContains applies the Contains predicate on the "font_mono" field.
func FontMonoContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldFontMono, v))
}

// FontMonoHasPrefix applies the HasPrefix predicate on the "font_mono" field.
func FontMonoHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldFontMono, v))
}

// FontMonoHasSuffix applies the HasSuffix predicate on the "font_mono" field.
func FontMonoHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldFontMono, v))
}

// FontMonoIsNil applies the IsNil predicate on the "font_mono" field.
func FontMonoIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldFontMono))
}

// FontMonoNotNil applies the NotNil predicate on the "font_mono" field.
func FontMonoNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldFontMono))
}

// FontMonoEqualFold applies the EqualFold predicate on the "font_mono" field.
func FontMonoEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldFontMono, v))
}

// FontMonoContainsFold applies the ContainsFold predicate on the "font_mono" field.
func FontMonoContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldFontMono, v))
}

// NavLogoPathEQ applies the EQ predicate on the "nav_logo_path" field.
func NavLogoPathEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldNavLogoPath, v))
}

// NavLogoPathNEQ applies the NEQ predicate on the "nav_logo_path" field.
func NavLogoPathNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldNavLogoPath, v))
}

// NavLogoPathIn applies the In predicate on the "nav_logo_path" field.
func NavLogoPathIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldNavLogoPath, vs...))
}

// NavLogoPathNotIn applies the NotIn predicate on the "nav_logo_path" field.
func NavLogoPathNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldNavLogoPath, vs...))
}

// NavLogoPathGT applies the GT predicate on the "nav_logo_path" field.
func NavLogoPathGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldNavLogoPath, v))
}

// NavLogoPathGTE applies the GTE predicate on the "nav_logo_path" field.
func NavLogoPathGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldNavLogoPath, v))
}

// NavLogoPathLT applies the LT predicate on the "nav_logo_path" field.
func NavLogoPathLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldNavLogoPath, v))
}

// NavLogoPathLTE applies the LTE predicate on the "nav_logo_path" field.
func NavLogoPathLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldNavLogoPath, v))
}

// NavLogoPathContains applies the Contains predicate on the "nav_logo_path" field.
func NavLogoPathContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldNavLogoPath, v))
}

// NavLogoPathHasPrefix applies the HasPrefix predicate on the "nav_logo_path" field.
func NavLogoPathHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldNavLogoPath, v))
}

// NavLogoPathHasSuffix applies the HasSuffix predicate on the "nav_logo_path" field.
func NavLogoPathHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldNavLogoPath, v))
}

// NavLogoPathIsNil applies the IsNil predicate on the "nav_logo_path" field.
func NavLogoPathIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldNavLogoPath))
}

// NavLogoPathNotNil applies the NotNil predicate on the "nav_logo_path" field.
func NavLogoPathNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldNavLogoPath))
}

// NavLogoPathEqualFold applies the EqualFold predicate on the "nav_logo_path" field.
func NavLogoPathEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldNavLogoPath, v))
}

// NavLogoPathContainsFold applies the ContainsFold predicate on the "nav_logo_path" field.
func NavLogoPathContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldNavLogoPath, v))
}

// SidebarLogoPathEQ applies the EQ predicate on the "sidebar_logo_path" field.
func SidebarLogoPathEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldSidebarLogoPath, v))
}

// SidebarLogoPathNEQ applies the NEQ predicate on the "sidebar_logo_path" field.
func SidebarLogoPathNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldSidebarLogoPath, v))
}

// SidebarLogoPathIn applies the In predicate on the "sidebar_logo_path" field.
func SidebarLogoPathIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldSidebarLogoPath, vs...))
}

// SidebarLogoPathNotIn applies the NotIn predicate on the "sidebar_logo_path" field.
func SidebarLogoPathNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldSidebarLogoPath, vs...))
}

// SidebarLogoPathGT applies the GT predicate on the "sidebar_logo_path" field.
func SidebarLogoPathGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldSidebarLogoPath, v))
}

// SidebarLogoPathGTE applies the GTE predicate on the "sidebar_logo_path" field.
func SidebarLogoPathGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldSidebarLogoPath, v))
}

// SidebarLogoPathLT applies the LT predicate on the "sidebar_logo_path" field.
func SidebarLogoPathLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldSidebarLogoPath, v))
}

// SidebarLogoPathLTE applies the LTE predicate on the "sidebar_logo_path" field.
func SidebarLogoPathLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldSidebarLogoPath, v))
}

// SidebarLogoPathContains applies the Contains predicate on the "sidebar_logo_path" field.
func SidebarLogoPathContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldSidebarLogoPath, v))
}

// SidebarLogoPathHasPrefix applies the HasPrefix predicate on the "sidebar_logo_path" field.
func SidebarLogoPathHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldSidebarLogoPath, v))
}

// SidebarLogoPathHasSuffix applies the HasSuffix predicate on the "sidebar_logo_path" field.
func SidebarLogoPathHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldSidebarLogoPath, v))
}

// SidebarLogoPathIsNil applies the IsNil predicate on the "sidebar_logo_path" field.
func SidebarLogoPathIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldSidebarLogoPath))
}

// SidebarLogoPathNotNil applies the NotNil predicate on the "sidebar_logo_path" field.
func SidebarLogoPathNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldSidebarLogoPath))
}

// SidebarLogoPathEqualFold applies the EqualFold predicate on the "sidebar_logo_path" field.
func SidebarLogoPathEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldSidebarLogoPath, v))
}

// SidebarLogoPathContainsFold applies the ContainsFold predicate on the "sidebar_logo_path" field.
func SidebarLogoPathContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldSidebarLogoPath, v))
}

// LoginIconPathEQ applies the EQ predicate on the "login_icon_path" field.
func LoginIconPathEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEQ(FieldLoginIconPath, v))
}

// LoginIconPathNEQ applies the NEQ predicate on the "login_icon_path" field.
func LoginIconPathNEQ(v string) predicate.Theme {
	return predicate.Theme(sql.FieldNEQ(FieldLoginIconPath, v))
}

// LoginIconPathIn applies the In predicate on the "login_icon_path" field.
func LoginIconPathIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldIn(FieldLoginIconPath, vs...))
}

// LoginIconPathNotIn applies the NotIn predicate on the "login_icon_path" field.
func LoginIconPathNotIn(vs ...string) predicate.Theme {
	return predicate.Theme(sql.FieldNotIn(FieldLoginIconPath, vs...))
}

// LoginIconPathGT applies the GT predicate on the "login_icon_path" field.
func LoginIconPathGT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGT(FieldLoginIconPath, v))
}

// LoginIconPathGTE applies the GTE predicate on the "login_icon_path" field.
func LoginIconPathGTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldGTE(FieldLoginIconPath, v))
}

// LoginIconPathLT applies the LT predicate on the "login_icon_path" field.
func LoginIconPathLT(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLT(FieldLoginIconPath, v))
}

// LoginIconPathLTE applies the LTE predicate on the "login_icon_path" field.
func LoginIconPathLTE(v string) predicate.Theme {
	return predicate.Theme(sql.FieldLTE(FieldLoginIconPath, v))
}

// LoginIconPathContains applies the Contains predicate on the "login_icon_path" field.
func LoginIconPathContains(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContains(FieldLoginIconPath, v))
}

// LoginIconPathHasPrefix applies the HasPrefix predicate on the "login_icon_path" field.
func LoginIconPathHasPrefix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasPrefix(FieldLoginIconPath, v))
}

// LoginIconPathHasSuffix applies the HasSuffix predicate on the "login_icon_path" field.
func LoginIconPathHasSuffix(v string) predicate.Theme {
	return predicate.Theme(sql.FieldHasSuffix(FieldLoginIconPath, v))
}

// LoginIconPathIsNil applies the IsNil predicate on the "login_icon_path" field.
func LoginIconPathIsNil() predicate.Theme {
	return predicate.Theme(sql.FieldIsNull(FieldLoginIconPath))
}

// LoginIconPathNotNil applies the NotNil predicate on the "login_icon_path" field.
func LoginIconPathNotNil() predicate.Theme {
	return predicate.Theme(sql.FieldNotNull(FieldLoginIconPath))
}

// LoginIconPathEqualFold applies the EqualFold predicate on the "login_icon_path" field.
func LoginIconPathEqualFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldEqualFold(FieldLoginIconPath, v))
}

// LoginIconPathContainsFold applies the ContainsFold predicate on the "login_icon_path" field.
func LoginIconPathContainsFold(v string) predicate.Theme {
	return predicate.Theme(sql.FieldContainsFold(FieldLoginIconPath, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Theme) predicate.Theme {
	return predicate.Theme(sql.NotPredicates(p))
}
